######################################################
##                                                  ##
##      SuperiorSkyblock2 - AcidIslands-Recoded     ##
##          Developed by Yoshiiro_ & Ome_R          ##
##                                                  ##
######################################################

# In questa sezione puoi scegliere quale tipologia di danno usare e configurare i loro vari parametri.
damage:
  # Tipologie esistenti: DEFAULT, POISON, NONE
  #######################################
  # DEFAULT: Utilizza il metodo predefinito del plugin con danno ogni secondo che aumenta col tempo.
  # POISON: Dà l'effetto di veleno al giocatore e il danno durerà nel tempo.
  # NONE: Nessun danno dall'acqua.
  type: DEFAULT
  # Parametri del danno di tipo DEFAULT
  default:
    # Il primo danno che verrà inflitto ai giocatori
    first-damage: 0.5
    # Ogni secondo, il danno sopra può essere moltiplicato. Puoi impostare il valore del moltiplicatore da qui.
    multiplier: 1.2
  poison:
    # Imposta i vari livelli di veleno nel formato "DOPO QUANTI SECONDI/LIVELLO POZIONE/DURATA"
    levels:
      - "0/1/5"
      - "5/2/10"
      - "10/3/15"
      - "15/4/20"
      - "20/5/30"

# In questa sezione puoi configurare la frequenza delle piogge acide e il mondo.
rain:
  # Mondo dove le piogge possono essere anche acide.
  world: Isola
  # Quando inizia a piovere questo valore viene usato per decidere se sarà una pioggia acida o no.
  # Inserisci un valore tra 0 e 1 dove 0 indica che tutte le piogge saranno normali e 1 indica che saranno tutte acide.
  rarity-percentage: 0.6
  # Messaggi che verranno inviati in chat agli utenti online per avvisare dell'inizio o della fine della pioggia acida.
  messages:
    acidrain-started: "&e&lAcidIsland | &7Una pioggia acida è iniziata nel mondo &fIsola&7. Mettiti al riparo prima che sia troppo tardi."
    acidrain-ended: "&e&lAcidIsland | &7La pioggia acida nel mondo &fIsola &7è finalmente terminata."

# In questa sezione puoi configurare tutte le funzioni dei PurifyingConduits, ovvero i condotti marini che purificano l'acqua entro un certo raggio.
# I conduits possono essere piazzati solo nelle isole, per piazzarli anche altrove bisogna avere il permesso: 'acidislands.purifyingconduit.bypass-place', ma saranno condotti puramente vanilla.
purifyngconduits:
  # Messaggi che verranno inviati in chat agli utenti online in determinate occasioni.
  messages:
    actbar-in-purified-water: "&7L'&fAcqua &7intorno a te è stata purificata."
    place-only-in-island: "&e&lAcidIsland | &7Puoi piazzare i &fCondotti Purificatori &7solo nelle isole."
  # Puoi configurare come meglio vuoi le caratteristiche dei vari livelli da qui.
  levels:
    # LIVELLO 1
    1:
      # Raggio purificazione dell'acqua.
      range: 5
    # LIVELLO 2
    2:
      # Raggio purificazione dell'acqua.
      range: 8
      # Prezzo upgrade da livello 1 a livello 2
      price: 5000
    # LIVELLO 3
    3:
      # Raggio purificazione dell'acqua.
      range: 10
      # Prezzo upgrade da livello 2 a livello 3
      price: 10000
    # LIVELLO 4
    4:
      # Raggio purificazione dell'acqua.
      range: 15
      # Prezzo upgrade da livello 3 a livello 4
      price: 250000
    # LIVELLO 5
    5:
      # Raggio purificazione dell'acqua.
      range: 20
      # Prezzo upgrade da livello 4 a livello 5
      price: 50000